/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import { Contract, Interface, type ContractRunner } from "ethers";
import type {
  INFTProto,
  INFTProtoInterface,
} from "../../../contracts/interfaces/INFTProto";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "recipient",
        type: "address",
      },
      {
        internalType: "string",
        name: "_tokenURI",
        type: "string",
      },
    ],
    name: "mintNFT",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
] as const;

export class INFTProto__factory {
  static readonly abi = _abi;
  static createInterface(): INFTProtoInterface {
    return new Interface(_abi) as INFTProtoInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): INFTProto {
    return new Contract(address, _abi, runner) as unknown as INFTProto;
  }
}
