/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as interfaces from "./interfaces";
export type { interfaces };
import type * as nftProtoSol from "./nftProto.sol";
export type { nftProtoSol };
